
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest  
    # ON which machine our project will work.

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    # this command tell to check the  current branch, by defauult it checkout main branch
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      # This command is just teling to setup nodejs environment before doing anything else and its optional
    
      with:
        node-version: ${{ matrix.node-version }}
        # Also we need to setup of other node version also
        cache: 'npm'
    - name: "installing Dependencies"   
      run: npm i
    - name: "Build command"
      run: npm run build --if-present
      


  deploy:
    name: 🚀 Deploy to Vercel
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📥 Install dependencies
        run: npm install

      - name: 🚀 Deploy with Vercel
        run: npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}